on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      with:
        server: ftp-zooarcadia.alwaysdata.net
        username: zooarcadia
        password: ${{ secrets.ftp_password }}
        protocol: ftps
        port: 21
        server-dir: /www/
          with:
        timeout: 600000
        passive: true
        exclude: |
          **/.git*
          **/.git*/**
          **/.github/**
    
          node_modules/**
          package.json
          package-lock.json
          yarn.lock
          pnpm-lock.yaml
    
          **/*.scss
          **/scss/**
          **/*.sass
          **/*.less
    
          **/node_modules/bootstrap/**
          **/node_modules/bootstrap-icons/**
    
          **/*.map
          **/webpack.config.js
          **/vite.config.js
    
          .DS_Store
          **/.DS_Store
          Thumbs.db
    
          **/php.ini
          **/composer.*
          **/Makefile
          **/README.md
